import { NextResponse } from "next/server";
import nodemailer from "nodemailer";

export async function POST(request) {
    try {
        const { name, email, phone, services, message, pageURL } = await request.json();
        const transporter = nodemailer.createTransport({
            service: "gmail",
            host: "smtp.gmail.com",
            port: 465,
            secure: true,
            auth: {
                user: 'signups@creativelogodesigns.io',
                pass: "10@Kskwoks"
            }
        });
        const mailOptions = {
            from: 'signups@creativelogodesigns.io',
            to: 'signups@creativelogodesigns.io',
            subject: `New Lead Generated By Creative Logo Designs`,
            html: `<div style="width:100%;height:100%;padding:1rem;background-color: #efefef;">
                <div style="display:flex; align-items: center;">
                    <h4>Name : ${name}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Email : ${email}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Phone : ${phone}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Services : ${services}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>Message : ${message}</h4>
                </div>
                <div style="display:flex; align-items: center;">
                    <h4>From : ${pageURL}</h4>
                </div>
            </div>`
        };
        await transporter.sendMail(mailOptions);
        return NextResponse.json({ "mesaage": "Email sent successfully", "status": 200 });
    } catch (error) {
        return NextResponse.json({ "mesaage": "Failed to sent Email", "status": 500 });
    }
}