// Meta Data
export const metadata = {
    // Title & Descriptions
    title: "Pricing & Packages - Creative Logo Designs",
    description: "Generated by Creative Logo Designs",
    // Google Varification
    verification: {
        other: {
            "facebook-domain-verification": ['9mgotld2pcip5yvdv6yajdqx71xfvt'],
        },
    },
    // Canonical
    alternates: {
        canonical: '/pricing',
    },
    openGraph: {
        title: "Pricing & Packages - Creative Logo Designs",
        description: "Generated by Creative Logo Designs",
        images: "/logo.png",
        url: "/pricing"
    },
}

export default function RootLayout({ children }) {
    return (children);
}